# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm i
      - persist_to_workspace:
          root: ~/project
          paths: .

  upload_codecov:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run:
          name: Upload codecov reports
          command: bash <(curl -s https://codecov.io/bash)

  release_npm:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  deploy:
    jobs:
      # Every commit
      - build:
          filters:
            tags:
              only: /.*/
      #Only when merged to master
      - upload_codecov:
          requires:
            - build
          filters:
            branches:
              only: master
      #On every new release
      - release_npm:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?$/
