export { isBoolean } from './isBoolean'
export { isNumber } from './isNumber'
export { isString } from './isString'
export { validate } from './validate'
export { validateRegex } from './validateRegex'
